<?php

$_dbstru = array(

  'Cfg' =>
  "Module varchar(60) ,
  Prop varchar(20),
  Val text,
  UNIQUE KEY  (Module, Prop)",

  'ApiTokens' =>
  "atID int(10) auto_increment,
  atuID int(10) not null,
  atName varchar(100) default '',
  atTokenHash char(64) not null,
  atScopes varchar(500) default '*',
  atState int(1) default 1,
  atCreatedAt bigint unsigned default 0,
  atExpiresAt bigint unsigned default 0,
  atLastUsedAt bigint unsigned default 0,
  atLastIP varchar(45) default '',
  PRIMARY KEY (atID),
  UNIQUE KEY ATTOKENHASH (atTokenHash),
  KEY ATUSER (atuID, atState)",

  'ApiRateLimits' =>
  "arlKey char(64) not null,
  arlWindow bigint unsigned not null,
  arlCount int unsigned default 0,
  arlUpdatedAt bigint unsigned default 0,
  PRIMARY KEY (arlKey, arlWindow),
  KEY ARLUPDATED (arlUpdatedAt)",

  'Installations' =>
  "tiID bigint unsigned auto_increment,
  tiPublicID char(36) not null,
  tiDomain varchar(253) not null,
  tiVersion varchar(32) not null,
  tiInstalledAt bigint unsigned default 0,
  tiRegisteredAt bigint unsigned default 0,
  tiLastSeenAt bigint unsigned default 0,
  tiLastReportAt bigint unsigned default 0,
  tiTokenHash char(64) not null,
  tiStatsConsent int(1) default 0,
  tiState int(1) default 1,
  tiLastIP varchar(45) default '',
  PRIMARY KEY (tiID),
  UNIQUE KEY TIPUBLICID (tiPublicID),
  KEY TIDOMAIN (tiDomain),
  KEY TILASTSEEN (tiState, tiLastSeenAt),
  KEY TIVERSION (tiVersion)",

  'InstallationReports' =>
  "tirID bigint unsigned auto_increment,
  tirInstallationID bigint unsigned not null,
  tirDay char(10) not null,
  tirVersion varchar(32) not null,
  tirStats json,
  tirCreatedAt bigint unsigned default 0,
  tirUpdatedAt bigint unsigned default 0,
  PRIMARY KEY (tirID),
  UNIQUE KEY TIRDAY (tirInstallationID, tirDay),
  KEY TIRUPDATED (tirUpdatedAt)",

  'TelemetryServiceTokens' =>
  "tstID int(10) auto_increment,
  tstuID int(10) not null,
  tstName varchar(100) default '',
  tstTokenHash char(64) not null,
  tstTokenPrefix varchar(16) default '',
  tstScope varchar(64) default 'telemetry:read',
  tstState int(1) default 1,
  tstCreatedAt bigint unsigned default 0,
  tstExpiresAt bigint unsigned default 0,
  tstLastUsedAt bigint unsigned default 0,
  tstLastIP varchar(45) default '',
  PRIMARY KEY (tstID),
  UNIQUE KEY TSTTOKENHASH (tstTokenHash),
  KEY TSTSTATE (tstState, tstExpiresAt),
  KEY TSTUSER (tstuID)",

  'Jobs' =>
  "jID int(10) auto_increment,
  jType varchar(50) not null,
  jPayload text not null,
  jState int(1) default 0,
  jAttempts int(2) default 0,
  jMaxAttempts int(2) default 3,
  jCTS bigint(14) default 0,
  jPTS bigint(14) default 0,
  jDTS bigint(14) default 0,
  jError text,
  PRIMARY KEY (jID),
  KEY JSTATE (jState, jCTS),
  KEY JTYPE (jType, jState)",

  'Hist' =>
  "hID int(10) auto_increment,
  hTS bigint(14) default 0,
  hOper varchar(10) default '',
  huID int(10) default 0,
  hIP varchar(15),
  hcID int(2) default 0,
  hSum decimal(13,6) default 0,
  hParams text,
  hTag int(10) default 0,
  hMemo varchar(60),
  hoID int(10) default 0,
  PRIMARY KEY  (hID),
  KEY HTS (hTS),
  KEY HTAG (hTag,hMemo)",

  'Users' =>
  "uID int(10)  auto_increment,
  uGroup varchar(40) default '',
  uLogin varchar(40) default '',
  uPass varchar(255) default '',
  uPass2 varchar(255) default '',
  uMail varchar(60) default '',
  uPIN varchar(255) default '',
  uState int(1) default 0,
  uBTS bigint(14),
  uLevel int(2) default 0,
  uLang varchar(10) default 'en',
  uMode varchar(10) default '',
  uTheme varchar(10) default '',
  uRef int(10) default 0,
  uBal decimal(13,6) default 0,
  uWDDisable int(1) default 0,
  uLTS bigint(14),
  uLIP varchar(15),
  uLSess varchar(32),
  uPTS bigint(14) default 0,
  uBFC int(1) default 0,
  PRIMARY KEY  (uID),
  UNIQUE KEY ULOGIN (uLogin),
  UNIQUE KEY UMAIL (uMail),
  KEY UREF (uRef),
  KEY ULTS (uLTS)",

  'AddInfo' =>
  "auID int(10) ,
  aName varchar(60) default '',
  aCTS bigint(14) default 0,
  aCIP varchar(15) default '',
  aSQuestion varchar(60),
  aSAnswer varchar(255),
  aPerc text,
  aDPerc text,
  aPPerc text,
  aIPSec int(1) default 0,
  aSessIP int(1) default 0,
  aSessUniq int(1) default 0,
  aTimeOut int(3) default 0,
  aOIDs text,
  aTZ int(4) default 0,
  aBD bigint(14) default 0,
  aCountry varchar(40) default '',
  aCity varchar(60) default '',
  aTel varchar(20) default '',
  aAvatar int(1) default 0,
  aDefCurr int(2) default 0,
  aNoMail int(1) default 0,
  aGA varchar(100),
  aNeedReConfig int(1) default 1,
  PRIMARY KEY  (auID)",

  'News' =>
  "nID int(5)  auto_increment,
  nDBegin bigint(14) default 0,
  nDEnd bigint(14) default 0,
  nTS bigint(14) default 0,
  nTopic varchar(1000) default '',
  nAnnounce text,
  nText text,
  nAttn int(1),
  PRIMARY KEY  (nID)",

  'Currs' => // CID - Currency ID (see PaymentManager) -> Name, Curr
  "cID int(2)  auto_increment,
  cDisabled int(1) default 1,
  cHidden int(1) default 0,
  cCID varchar(4) default '',
  cCurrID varchar(10) default '',
  cName varchar(120) default '',
  cCurr varchar(60) default '',
  cParams text,
  cParamsSCI text,
  cParamsAPI text,
  cNumDec int(1) default 0,
  cCASHINMode int(1) default 1,
  cCASHINMin decimal(13,6) default 0,
  cCASHINMax decimal(13,6) default 0,
  cCASHINInt int(1) default 0,
  cCASHINComis decimal(6,2) default 0,
  cCASHINComisMin decimal(13,6) default 00,
  cCASHINComisMax decimal(13,6) default 00,
  cCASHOUTMode int(1) default 0,
  cCASHOUTMin decimal(13,6) default 0,
  cCASHOUTMax decimal(13,6) default 0,
  cCASHOUTInt int(1) default 0,
  cCASHOUTComis decimal(6,2) default 0,
  cCASHOUTComisMin decimal(13,6) default 00,
  cCASHOUTComisMax decimal(13,6) default 00,
  cCASHOUTLimitPer int(3) default 0,
  cCASHOUTLimit decimal(13,6) default 0,
  cEXMode int(1) default 0,
  cEXOut decimal(10,6) default 0,
  cEXIn decimal(10,6) default 0,
  cEXMin decimal(13,6) default 0,
  cEXMax decimal(13,6) default 0,
  cEXInt int(1) default 0,
  cEXComis decimal(6,2) default 0,
  cEXComisMin decimal(13,6) default 00,
  cEXComisMax decimal(13,6) default 00,
  cTRMode int(1) default 0,
  cTRMin decimal(13,6) default 0,
  cTRMax decimal(13,6) default 0,
  cTRInt int(1) default 0,
  cTRComis decimal(6,2) default 0,
  cTRComisMin decimal(13,6) default 00,
  cTRComisMax decimal(13,6) default 00,
  cBUYMode int(1) default 0,
  cSELLMode int(1) default 0,
  cBUY2Mode int(1) default 0,
  cSELL2Mode int(1) default 0,
  cGIVEMode int(1) default 0,
  cTAKEMode int(1) default 0,
  cMTS bigint(14),
  cBalMin decimal(13,6) default 0,
  cBal decimal(13,6) default 0,
  cBalTS bigint(14),
  PRIMARY KEY  (cID)", // cParams - IN (public) wallet, cParams2 - OUT (private) wallet

 'Wallets' =>
 "wcID int(2) default 0,
  wuID int(10) default 0,
  wBal decimal(13,6) default 0,
  wLock decimal(13,6) default 0,
  wOut decimal(13,6) default 0,
  wParams text,
  wMTS bigint(14),
  PRIMARY KEY  (wcID,wuID)",

    'Opers' =>
  "oID int(10)  auto_increment,
  oCTS bigint(14),
  oATS bigint(14),
  ouID int(10),
  oOper varchar(10),
  ocID int(2),
  oSum decimal(13,6) default 0,
  oComis decimal(13,6) default 0,
  oParams text,
  oParams2 text,
  oBatch varchar(40),
  oTag varchar(60),
  oTS bigint(14),
  oState int(1) default 0,
  oPTS bigint(14) default 0,
  oMemo varchar(120),
  oNTS bigint(14),
  PRIMARY KEY  (oID),
  KEY OBATCH (ocID,oBatch),
  KEY OTAG (oTag)", // oParams2 - additional parameters (for ex. deposit)

    'Calend'=>
        "cID int(6)  auto_increment,
         cTS bigint(14) default 0,
         cYear int(4),
         cMonth int(2),
         cDay int(2),
         cType int(1),
         cPerc decimal(7,2) default 0,
         PRIMARY KEY  (cID),
         KEY CTS (cTS),
         KEY CDAY (cYear,cMonth,cDay)",

    /*'Banners' =>
     "rID int(10)  auto_increment,
      rDisabled int(1) default 1,
      rDBegin bigint(14) ,
      rDEnd bigint(14) ,
      rPlace int(4),
      rName varchar(120),
      rPictURL varchar(500),
      rGoURL varchar(500),
      rWeeks int(3),
      PRIMARY KEY  (rID)",*/

    'Plans' =>
  "pID int(3)  auto_increment,
  pHidden int(1) default 0,
  pNoCalc int(1) default 0,
  pGroup int(2) default 0,
  pGroupReq int(2) default 0,
  pMaxCount int(3) default 0,
  pName varchar(400) default '',
  pDescr varchar(1000) default '',
  pMin decimal(13,6) default 1.00,
  pMax decimal(13,6) default 0,
  pDays int(5) default 0,
  pWDays int(1) default 0,
  pPerc decimal(7,2) default 0,
  pCompndMin decimal(7,2) default 0,
  pCompndMax decimal(7,2) default 0,
  pPer int(6) default 0,
  pNPer int(5) default 0,
  pReturn decimal(7,2) default 100.00,
  pMPer int(5) default 0,
  pClPer int(5) default 0,
  pClComis decimal(7,2) default 100.00,
  pBonus decimal(7,2) default 0,
  pEnAdd int(1) default 0,
  pMinAdd decimal(13,6) default 1.00,
  pDPerc text,
  pPPerc text,
  pPClndr int(1) default 0,
  pmndID int(10) default 0,
  pmndIDdone int(10) default 0,
  pmnPerc decimal(7,2) default 0,
  PRIMARY KEY  (pID)",

    'Deps' =>
  "dID int(10)  auto_increment,
  duID int(10) default 0,
  dState int(1) default 0,
  dpID int(3) default 0,
  dCTS bigint(14) default 0,
  dETS bigint(14) default 0,
  dcID int(2) default 0,
  dZ0 decimal(13,6) default 0,
  dZD decimal(13,6) default 0,
  dCompnd decimal(7,2) default 0,
  dZC decimal(13,6) default 0,
  dNTS bigint(14) default 0,
  dLTS bigint(14) default 0,
  dZP decimal(13,6) default 0,
  dNPer int(5) default 0,
  PRIMARY KEY  (dID),
  KEY AUID (duID),
  KEY ACTS (dCTS)",

    'Review' =>
  "oID int(10)  auto_increment,
  oTS bigint(14) default 0,
  ouID int(10) default 0,
  oText text,
  oRating tinyint unsigned NOT NULL default 5,
  oOrder int(3) default 0,
  oState int(1) default 0,
  PRIMARY KEY  (oID)",

    'FAQ' =>
  "fID int(5)  auto_increment,
  fHidden int(1) default 0,
  fCTS bigint(14) default 0,
  fCat varchar(100) default '',
  fOrder int(3) default 0,
  fQuestion varchar(2000) default '',
  fAnswer text,
  PRIMARY KEY  (fID)",

    'Tickets' =>
  "tID int(10)  auto_increment,
  tuID int(10) default 0,
  tTS bigint(14) default 0,
  tTID varchar(32) default '',
  tName varchar(60) default '',
  tMail varchar(60) default '',
  tCat varchar(100) default '',
  tTopic varchar(200),
  tText text,
  tPriority int(1),
  tState int(1),
  tLang varchar(10) default 'en',
  tLTS bigint(14),
  PRIMARY KEY  (tID),
  KEY TUID (tuID)",

    'TMsg' =>
  "mID int(10)  auto_increment,
  mtID int(10) default 0,
  muID int(10) default 0,
  mTS bigint(14) default 0,
  mText text,
  mRTS bigint(14),
  PRIMARY KEY  (mID),
  KEY MTID (mtID)",

    'Msg' =>
 "mID int(10)  auto_increment,
  muID int(10) default 0,
  mTS bigint(14) default 0,
  mMail varchar(60) default '',
  mAttn int(1),
  mTopic varchar(120) default 0,
  mText text,
  mLang varchar(10) default 'en',
  mGroup int(10) default 0,
  mTo text,
  mToCnt int(6) default 0,
  PRIMARY KEY  (mID),
  KEY MUID (muID)",

    'MBox' =>
 "bID int(10)  auto_increment,
  buID int(10) default 0,
  bmID int(10) default 0,
  bRe int(10) default 0,
  buID2 int(10) default 0,
  bMail varchar(60) default '',
  bRTS bigint(14) default 0,
  bDeleted int(1) default 0,
  PRIMARY KEY  (bID),
  KEY BUID (buID),
  KEY BUID2 (buID2),
  KEY BMID (bmID)"

);
