<?php

namespace HScript\Security;

use HScript\Application;
use HScript\Update\ReleaseBaselineRepository;
use HScript\Update\ReleaseInventory;
use RuntimeException;
use Throwable;

final class IntegrityScanner
{
	private const EXECUTABLE_EXTENSIONS = array('php', 'php3', 'php4', 'php5', 'php7', 'php8', 'phtml', 'phar');
	private const SPECIAL_ROOTS = array(
		'upload' => true,
		'cache' => true,
		'tmp' => true,
		'logs' => true,
		'backup' => true,
		'tpl/themes' => true,
		// These two directories contain PHP generated by the template runtime.
		// Links are still rejected, but generated executable files are expected.
		'compile' => false,
		'tpl_c' => false,
	);
	private const DEVELOPMENT_ROOTS = array('.agents', '.codex', '.git', 'dist', 'node_modules', 'tests');

	private string $root;
	private array $baseline;
	private string $baselineSource;
	private string $baselineChecksum;
	private IntegrityStateRepository $states;
	private int $batchFiles;
	private float $maximumSeconds;
	private int $maximumFiles;
	private int $maximumFindings;

	public function __construct(
		string $projectRoot,
		?array $baseline = null,
		?IntegrityStateRepository $states = null,
		?int $batchFiles = null,
		?float $maximumSeconds = null
	) {
		$root = realpath($projectRoot);
		if ($root === false || !is_dir($root)) throw new RuntimeException('Project root could not be resolved');
		$this->root = rtrim($root, '/');
		$this->states = $states ?? new IntegrityStateRepository($this->root);
		$this->batchFiles = $batchFiles ?? $this->integerEnvironment('INTEGRITY_SCAN_BATCH_FILES', 1000, 10, 10000);
		$this->maximumSeconds = $maximumSeconds ?? $this->integerEnvironment('INTEGRITY_SCAN_MAX_SECONDS', 10, 1, 25);
		$this->maximumFiles = $this->integerEnvironment('INTEGRITY_SCAN_MAX_FILES', 20000, 100, 100000);
		$this->maximumFindings = $this->integerEnvironment('INTEGRITY_SCAN_MAX_FINDINGS', 500, 10, 5000);
		if ($baseline === null)
		{
			$version = Application::version();
			$work = trim((string)(getenv('UPDATE_WORK_PATH') ?: '')) ?: $this->root . '/.cfg/update';
			try { $baseline = ReleaseBaselineRepository::read($work . '/baselines/installed.json', $version); }
			catch (Throwable $exception)
			{
				$baseline = null;
				error_log('Installed integrity baseline ignored: ' . $exception->getMessage());
			}
			$this->baselineSource = 'installed-release';
			if ($baseline === null)
			{
				$baseline = ReleaseBaselineRepository::read($this->root . '/resources/release-baseline.json', $version);
				$this->baselineSource = 'bundled-release';
			}
			if ($baseline === null) throw new RuntimeException('Verified release integrity baseline is not available');
		}
		else
			$this->baselineSource = 'test';
		$this->baseline = $this->validateBaseline($baseline);
		$this->baselineChecksum = hash('sha256', json_encode($this->baseline, JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR));
	}

	public function start(): array
	{
		return $this->states->locked(fn(): array => $this->startUnlocked());
	}

	private function startUnlocked(): array
	{
		$previous = $this->states->get();
		$state = array(
			'format' => 1,
			'status' => 'running',
			'scan_id' => bin2hex(random_bytes(16)),
			'baseline_version' => Application::version(),
			'baseline_source' => $this->baselineSource,
			'baseline_checksum' => $this->baselineChecksum,
			'cursor' => 0,
			'total' => 0,
			'checked' => 0,
			'started_at' => time(),
			'updated_at' => time(),
			'completed_at' => 0,
			'findings' => array(),
			'findings_truncated' => false,
			'critical_keys' => array(),
			'counts' => $this->emptyCounts(),
			'previous_alert_signature' => (string)($previous['alert_signature'] ?? ''),
			'alert_signature' => '',
			'new_alert' => false,
			'acknowledged_signature' => (string)($previous['acknowledged_signature'] ?? ''),
			'acknowledged_at' => (int)($previous['acknowledged_at'] ?? 0),
			'notified_signature' => (string)($previous['notified_signature'] ?? ''),
			'notified_at' => (int)($previous['notified_at'] ?? 0),
		);
		$this->states->save($state);
		return $this->advanceUnlocked();
	}

	public function advance(): array
	{
		return $this->states->locked(function (): array {
			$state = $this->states->get();
			// A cursor belongs to one verified release; never mix two inventories.
			if ($state !== null && !$this->matchesBaseline($state)) return $this->startUnlocked();
			// Another browser or cron may have finished the last batch already.
			if (($state['status'] ?? '') === 'completed') return $state;
			return $this->advanceUnlocked();
		});
	}

	public function matchesBaseline(array $state): bool
	{
		return ($state['baseline_version'] ?? '') === Application::version()
			&& hash_equals((string)($state['baseline_checksum'] ?? ''), $this->baselineChecksum);
	}

	private function advanceUnlocked(): array
	{
		$state = $this->states->get();
		if ($state === null || ($state['status'] ?? '') !== 'running')
			throw new RuntimeException('There is no running integrity scan');
		if (!hash_equals((string)($state['baseline_checksum'] ?? ''), $this->baselineChecksum))
			throw new RuntimeException('Integrity baseline changed during scan');
		try
		{
			$tasks = $this->tasks();
			$state['total'] = count($tasks);
			$deadline = microtime(true) + $this->maximumSeconds;
			$processed = 0;
			while ((int)$state['cursor'] < count($tasks) && $processed < $this->batchFiles && microtime(true) < $deadline)
			{
				$this->inspectTask($tasks[(int)$state['cursor']], $state);
				$state['cursor']++;
				$state['checked']++;
				$processed++;
			}
			$state['updated_at'] = time();
			if ((int)$state['cursor'] >= count($tasks))
			{
				$state['status'] = 'completed';
				$state['completed_at'] = time();
				$signature = $state['critical_keys'] ? hash('sha256', implode("\n", $state['critical_keys'])) : '';
				$state['alert_signature'] = $signature;
				$state['new_alert'] = $signature !== '' && !hash_equals((string)$state['previous_alert_signature'], $signature);
			}
			$this->states->save($state);
			return $state;
		}
		catch (Throwable $exception)
		{
			$state['status'] = 'failed';
			$state['updated_at'] = time();
			$state['error_code'] = 'scan_failed';
			$state['error_summary'] = 'Integrity scan stopped; inspect the protected server log';
			$this->states->save($state);
			error_log('Integrity scan failed: ' . $exception->getMessage());
			throw $exception;
		}
	}

	public function status(): ?array { return $this->states->get(); }
	public function acknowledge(): array { return $this->states->acknowledge(); }

	private function tasks(): array
	{
		$actual = $this->managedActualFiles();
		$tasks = array();
		foreach ($this->baseline as $path => $expected)
		{
			$tasks[] = array('type' => 'expected', 'path' => $path, 'expected' => $expected);
			unset($actual[$path]);
		}
		foreach ($actual as $path => $type)
		{
			if ($path === 'resources/release-baseline.json') continue;
			$tasks[] = array('type' => 'unexpected', 'path' => $path, 'actual_type' => $type);
		}
		foreach ($this->specialTasks() as $task) $tasks[] = $task;
		usort($tasks, static fn(array $left, array $right): int => strcmp($left['type'] . "\0" . $left['path'], $right['type'] . "\0" . $right['path']));
		if (count($tasks) > $this->maximumFiles) throw new RuntimeException('Integrity scan exceeds the configured file limit');
		return $tasks;
	}

	private function inspectTask(array $task, array &$state): void
	{
		$path = ReleaseInventory::requireSafePath($task['path']);
		$absolute = $this->root . '/' . $path;
		if ($task['type'] === 'expected')
		{
			$expected = $task['expected'];
			$class = $expected['class'];
			if (is_link($absolute))
			{
				$this->finding($state, $path, 'unexpected_link', $class, 'critical', $expected['size'], null, @filemtime($absolute) ?: 0);
				return;
			}
			if (!is_file($absolute))
			{
				$this->finding($state, $path, $class === 'customizable' ? 'customized' : 'missing', $class, $class === 'customizable' ? 'neutral' : 'critical', $expected['size'], null, 0);
				return;
			}
			// The file may disappear or lose read access between inventory and
			// inspection. Treat that race as a finding instead of leaking a PHP
			// warning into the Configurator response.
			$size = @filesize($absolute);
			$mtime = @filemtime($absolute);
			$checksum = is_readable($absolute) ? @hash_file('sha256', $absolute) : false;
			if (!is_int($size) || !is_int($mtime) || !is_string($checksum))
			{
				$this->finding($state, $path, 'unreadable', $class, 'critical', $expected['size'], is_int($size) ? $size : null, is_int($mtime) ? $mtime : 0);
				return;
			}
			if ($size !== $expected['size'] || !hash_equals($expected['sha256'], $checksum))
			{
				$this->finding($state, $path, $class === 'customizable' ? 'customized' : 'modified', $class, $class === 'customizable' ? 'neutral' : 'critical', $expected['size'], $size, $mtime);
				return;
			}
			$state['counts']['unchanged']++;
			return;
		}

		if (!file_exists($absolute) && !is_link($absolute)) return;
		$mtime = @filemtime($absolute) ?: 0;
		$size = is_file($absolute) ? @filesize($absolute) : null;
		if ($task['type'] === 'special')
			$this->finding(
				$state,
				$path,
				$task['status'],
				$task['class'] ?? 'runtime',
				$task['severity'] ?? 'critical',
				null,
				is_int($size) ? $size : null,
				$mtime
			);
		else
		{
			$customizable = str_starts_with($path, 'tpl/') && str_ends_with(strtolower($path), '.twig');
			$extension = strtolower(pathinfo($path, PATHINFO_EXTENSION));
			$executable = in_array($extension, self::EXECUTABLE_EXTENSIONS, true) || $this->hasExecutableMode($absolute);
			$status = $customizable ? 'customized' : ($task['actual_type'] === 'link' ? 'unexpected_link' : ($executable ? 'unexpected_executable' : 'unexpected'));
			$this->finding($state, $path, $status, $customizable ? 'customizable' : 'core_strict', $customizable ? 'neutral' : 'critical', null, is_int($size) ? $size : null, $mtime);
		}
	}

	private function finding(array &$state, string $path, string $status, string $class, string $severity, ?int $expectedSize, ?int $actualSize, int $mtime): void
	{
		$key = $path . '|' . $status . '|' . $severity;
		if ($severity === 'critical')
		{
			$state['counts']['critical']++;
			$state['critical_keys'][] = $key;
		}
		if ($status === 'customized') $state['counts']['customized']++;
		elseif ($status === 'modified') $state['counts']['modified']++;
		elseif ($status === 'missing') $state['counts']['missing']++;
		elseif (str_starts_with($status, 'unexpected')) $state['counts']['unexpected']++;
		else $state['counts']['errors']++;
		if (count($state['findings']) >= $this->maximumFindings)
		{
			$state['findings_truncated'] = true;
			return;
		}
		$state['findings'][] = array(
			'path' => $path,
			'status' => $status,
			'class' => $class,
			'severity' => $severity,
			'expected_size' => $expectedSize,
			'actual_size' => $actualSize,
			'mtime' => $mtime,
			'checked_at' => time(),
		);
	}

	private function managedActualFiles(): array
	{
		$result = array();
		$stack = array(array($this->root, ''));
		while ($stack)
		{
			[$directory, $prefix] = array_pop($stack);
			$items = @scandir($directory);
			if (!is_array($items)) throw new RuntimeException('Integrity directory could not be read: ' . ($prefix ?: '.'));
			foreach ($items as $name)
			{
				if ($name === '.' || $name === '..') continue;
				$path = $prefix === '' ? $name : $prefix . '/' . $name;
				if ($prefix === '' && in_array($name, self::DEVELOPMENT_ROOTS, true)) continue;
				if (ReleaseInventory::preserved($path)) continue;
				$absolute = $directory . '/' . $name;
				if (is_link($absolute)) { $result[$path] = 'link'; continue; }
				if (is_dir($absolute)) { $stack[] = array($absolute, $path); continue; }
				if (is_file($absolute)) $result[$path] = 'file';
				else $result[$path] = 'special';
				if (count($result) > $this->maximumFiles) throw new RuntimeException('Integrity inventory exceeds the configured file limit');
			}
		}
		ksort($result, SORT_STRING);
		return $result;
	}

	private function specialTasks(): array
	{
		$result = array();
		foreach (self::SPECIAL_ROOTS as $root => $forbidExecutables)
		{
			$absolute = $this->root . '/' . $root;
			if (!is_dir($absolute) && !is_link($absolute)) continue;
			$this->walkSpecial($absolute, $root, $result, $forbidExecutables, true, $root === 'tpl/themes');
		}
		return $result;
	}

	private function walkSpecial(string $directory, string $prefix, array &$result, bool $forbidExecutables, bool $top = false, bool $reportCustomizations = false): void
	{
		if (is_link($directory))
		{
			if (!$top) { $result[] = array('type' => 'special', 'path' => $prefix, 'status' => 'unexpected_link'); return; }
			$resolved = realpath($directory);
			if ($resolved === false || !is_dir($resolved)) { $result[] = array('type' => 'special', 'path' => $prefix, 'status' => 'unexpected_link'); return; }
			$directory = $resolved;
		}
		$items = @scandir($directory);
		if (!is_array($items)) { $result[] = array('type' => 'special', 'path' => $prefix, 'status' => 'unreadable'); return; }
		foreach ($items as $name)
		{
			if ($name === '.' || $name === '..') continue;
			$path = $prefix . '/' . $name;
			$absolute = $directory . '/' . $name;
			if (is_link($absolute)) { $result[] = array('type' => 'special', 'path' => $path, 'status' => 'unexpected_link'); continue; }
			if (is_dir($absolute)) { $this->walkSpecial($absolute, $path, $result, $forbidExecutables, false, $reportCustomizations); continue; }
			$extension = strtolower(pathinfo($name, PATHINFO_EXTENSION));
			if ($forbidExecutables && (in_array($extension, self::EXECUTABLE_EXTENSIONS, true) || $this->hasExecutableMode($absolute)))
				$result[] = array('type' => 'special', 'path' => $path, 'status' => 'unexpected_executable');
			elseif ($reportCustomizations && !isset($this->baseline[$path]))
				$result[] = array('type' => 'special', 'path' => $path, 'status' => 'customized', 'class' => 'customizable', 'severity' => 'neutral');
		}
	}

	private function hasExecutableMode(string $path): bool
	{
		// is_executable() may return true for uid 0 on bind-mounted files even
		// when no execute bit is present. Integrity policy follows the actual
		// Unix mode so a normal 0644 runtime file stays neutral.
		$mode = @fileperms($path);
		return is_int($mode) && ($mode & 0111) !== 0;
	}

	private function validateBaseline(array $baseline): array
	{
		$result = array();
		foreach ($baseline as $path => $entry)
		{
			$path = ReleaseInventory::requireSafePath($path);
			if (!is_array($entry) || !is_string($entry['sha256'] ?? null) || !preg_match('/^[a-f0-9]{64}$/', $entry['sha256'])
				|| !is_int($entry['size'] ?? null) || $entry['size'] < 0
				|| !in_array($entry['class'] ?? null, array('core_strict', 'customizable'), true))
				throw new RuntimeException('Integrity baseline entry is invalid');
			if (str_starts_with($path, 'tpl/themes/') || (str_starts_with($path, 'tpl/') && str_ends_with(strtolower($path), '.twig')))
				$entry['class'] = 'customizable';
			$result[$path] = array('sha256' => $entry['sha256'], 'size' => $entry['size'], 'class' => $entry['class']);
		}
		ksort($result, SORT_STRING);
		if (!$result || count($result) > $this->maximumFiles) throw new RuntimeException('Integrity baseline file count is invalid');
		return $result;
	}

	private function emptyCounts(): array
	{
		return array('unchanged' => 0, 'modified' => 0, 'missing' => 0, 'customized' => 0, 'unexpected' => 0, 'errors' => 0, 'critical' => 0);
	}

	private function integerEnvironment(string $name, int $default, int $minimum, int $maximum): int
	{
		$value = getenv($name);
		$value = is_string($value) && ctype_digit($value) ? (int)$value : $default;
		return max($minimum, min($maximum, $value));
	}
}
